name: transaction-outbox-service

services:
  postgres:
    image: postgres:17.10-alpine
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payments -d payments"]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka:
    image: apache/kafka:4.1.2
    ports:
      - "9092:9092"
    healthcheck:
      test:
        - CMD-SHELL
        - /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list >/dev/null 2>&1
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

volumes:
  postgres-data:
